language: ruby
rvm:
  - 2.4.2

before_install:
  - sudo apt-get install nmap
  - sudo apt-get install wget
  - sudo apt-get install libcurl4-openssl-dev

before_script:
  - ./set_token.sh
  - bundle exec rake db:drop || true
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:seed
  - bundle exec rails s -d

script:
  - bundle exec rake secure_pipeline:network_attack
  - bundle exec rake secure_pipeline:ssl_attack
  - bundle exec rake secure_pipeline:xss
  - bundle exec rake secure_pipeline:information_leakage
  - bundle exec rake secure_pipeline:sql_injection